name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

  postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: bankdb
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U user -d bankdb" --health-timeout=30s --health-retries=3

  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variables
        run: |
          export DATABASE_URL=postgresql://user:password@localhost:5432/bankdb

      - name: Run Tests
        run: pytest
# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     services:
#       postgres:
#         image: postgres:13
#         env:
#           POSTGRES_USER: user
#           POSTGRES_PASSWORD: password
#           POSTGRES_DB: bankdb
#         ports:
#           - 5432:5432
#         options: --health-cmd="pg_isready -U user -d bankdb" --health-timeout=30s --health-retries=3
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v3
#         with:
#           python-version: "3.10"

#       - name: Install Dependencies
#         run: pip install -r requirements.txt

#       - name: Set Environment Variables
#         run: |
#           export DATABASE_URL=postgresql://user:password@localhost:5432/bankdb

#       - name: Run Tests
#         run: pytest

###############################
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v3
#         with:
#           python-version: "3.10"

#       - name: Install Dependencies
#         run: pip install -r requirements.txt

#       - name: Set PYTHONPATH for tests
#         run: |
#           export PYTHONPATH=$(pwd)
#         # pytest

#   build-and-deploy:
#     needs: test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

# - name: Log in to DockerHub
# run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

# - name: Build and Push Docker Image
# run: |
# docker build -t mydockerhub/fastapi-bank:latest .
# docker push mydockerhub/fastapi-bank:latest

# - name: Deploy to Kubernetes
# run: |
# kubectl apply -f k8s/
